### PR TITLE
Add get pid

### PR DESCRIPTION
**Pull request by plexus**
Add some more convenience, a getter for the PID, and a `Process#kill` method.

@headius feel free to tell me if this is not appropriate or if you expect a higher level of quality from patches :) (also goes for #1)

### CODE REVIEW

**Comment by enebo** [comment]
@plexus A couple of comments (not sure how active @headius will be this week due to travelling) to help keep this moving: 1) SIGKILL should come from dependent maven jar jnr-constants.  That jar defines all the OS-specific values (which probably would not be an issue for SIGKILL but we should just source from it anyways). 2) pid is a long in one place and you cast down to an int in another.  Does it need to be like that?

**Comment by enebo** [comment]
Just added the dep to pom.xml for this:

[master f861c0d] Add jnr-constants so that we can pull in platform-specific constants for process management

**Comment by plexus** [comment]
@enebo thanks for the feedback, very much appreciated! I'll see if I can source the signal number from jnr-constants.

The long/int thing is because the `jnr.posix.POSIX` interface isn't consistent. `posix_spawnp` returns a long, but `kill` requires an int. 

```
    public long posix_spawnp(String path, Collection<? extends SpawnFileAction> fileActions,
                            Collection<? extends CharSequence> argv, Collection<? extends CharSequence> envp);

    int kill(int pid, int signal);
```

Digging a bit deeper it seems `jnr.posix` is wrong, the C function returns an int, I guess it should be fixed there.

http://pubs.opengroup.org/onlinepubs/009695399/functions/posix_spawn.html

**Comment by plexus** [comment]
It was changed in jnr/jnr-posix@922259d97e116e6e6c4be3c248237c81939b17f9 from `int` to `long`. Advice on how to proceed?

**Comment by plexus** [comment]
seems on Windows a PID is stored in a DWORD, which would need a java Long. This would require quite some updates though to make the API consistent.

```
10 matches in 8 lines for "pid" in buffer: POSIX.java
     47:    int getpgid(int pid);
     49:    int getpid();
     50:    int getppid();
     64:    int kill(int pid, int signal);
     78:    int setpgid(int pid, int pgid);
     79:    int setpgrp(int pid, int pgrp);
     89:    int waitpid(int pid, int[] status, int flags);
     90:    int waitpid(long pid, int[] status, int flags);
```

**Comment by headius** [comment]
We should always use the widest type that will work across all platforms. I believe most of these APIs should be adjusted to long. I fixed a couple recently.

**Comment by plexus** [comment]
alright, will see what I can do!

**Comment by plexus** [comment]
Made a PR to add a long-receiving version of kill: https://github.com/jnr/jnr-posix/pull/41

**Comment by plexus** [comment]
Made a new PR for the kill implementation (#4). Leaving `getPid` out for now, with kill available I don't really need it.

**Pull request closed without merging**
